//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace finalDBMSPRo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductIngredient
    {
        public int Proc_Ing_id { get; set; }
        public string Proc_Ing_Name { get; set; }
        public Nullable<int> Product_id { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
